name: Dependabot → Copilot CLI review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  copilot-cli-review:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    env:
      # Fine-grained PAT with "Copilot Requests" permission.
      # Add it in repo/org secrets as COPILOT_PAT.
      GITHUB_TOKEN: ${{ secrets.COPILOT_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable pnpm

      - name: Setup Node (Copilot CLI needs Node 22+)
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Copilot CLI
        run: npm i -g @github/copilot

      - name: Build prompt (inline your rubric)
        id: prompt
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          cat > /tmp/prompt.txt <<'TXT'
          You are reviewing a Dependabot PR.
          Output **GitHub Markdown only**, no code fences, use real line breaks.

          PR: ${PR_URL}
          Title: ${PR_TITLE}

          Follow the rubric **exactly**:

          <<<RUBRIC
          TXT
          # append the rubric file verbatim
          cat .github/instructions/dependabot-pr-instructions.md >> /tmp/prompt.txt
          echo -e "\nRUBRIC" >> /tmp/prompt.txt

      - name: Run Copilot CLI (no tools)
        run: |
          copilot --deny-tool='*' < /tmp/prompt.txt > /tmp/review.md

      - name: Post review as PR comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs')
            const body = fs.readFileSync('/tmp/review.md','utf8')
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.payload.pull_request.number,
              body
            })
