name: Dependabot → Copilot CLI review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

env:
  # Fine-grained PAT with "Copilot Requests" permission
  GITHUB_TOKEN: ${{ secrets.COPILOT_PAT }}
  XDG_CONFIG_HOME: $RUNNER_TEMP/.config

jobs:
  copilot-cli-review:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Enable Corepack
        run: corepack enable pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22 # Copilot CLI requires Node.js 22+
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Copilot CLI
        run: npm i -g @github/copilot

      # simplest: allow all tools + allow the workspace directory
      - name: Run Copilot CLI
        run: |
          copilot \
          --model claude-sonnet-4.5 \
          --allow-all-tools \
          --deny-tool 'shell(git push)'
          --add-dir "$GITHUB_WORKSPACE" \
          -p "Review this Dependabot PR using the repo’s Copilot instructions.
          PR: ${{ github.event.pull_request.html_url }}
          Title: ${{ github.event.pull_request.title }}
          Output GitHub Markdown only, no code fences." \
          > /tmp/review.md

      - name: Post review as PR comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-path: /tmp/review.md
