name: Discover Copilot Reviewer API Format

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: read

jobs:
  discover:
    runs-on: ubuntu-latest
    steps:
      - name: Show reviewer names
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api "/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
            --jq '.requested_reviewers[].login'
