name: Discover Copilot Reviewer API Format

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: read

jobs:
  discover:
    runs-on: ubuntu-latest
    steps:
      - name: Show all reviewer data
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "=== Requested Reviewers ==="
          gh api "/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
            --jq '.requested_reviewers'

          echo ""
          echo "=== Requested Teams ==="
          gh api "/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
            --jq '.requested_teams'
